server:
  port: ${port:9090}
mybatis:
  type-aliases-package: com.itheima.producer.pojo
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/day23
    username: root
    password: 123456
  application:
    name: producer
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 5

test:
  name: haoziweiz
